### ISSUE TITLE
Saving manifest causes cf to crash

### ISSUE THREAD

**Issue by scothis** [cloudfoundry-attic/cf#28]
```
$ cf push
<snip>

Save configuration?> y

Upload failed. Try again with 'cf push'.
NoMethodError: undefined method `host' for #<CFoundry::V2::App '50865916-5ff0-4b3f-add3-7a3271574c0b'>
cat ~/.cf/crash # for more details
```

```
Time of crash:
  Tue Jul 09 18:02:53 -0400 2013

NoMethodError: undefined method `host' for #<CFoundry::V2::App '50865916-5ff0-4b3f-add3-7a3271574c0b'>

cf-4.1.1/lib/manifests/manifests.rb:172:in `create_manifest_for'
cf-4.1.1/lib/manifests/manifests.rb:248:in `ask_to_save'
cf-4.1.1/lib/manifests/plugin.rb:136:in `create_and_save_manifest'
mothership-0.5.1/lib/mothership/callbacks.rb:55:in `instance_exec'
mothership-0.5.1/lib/mothership/callbacks.rb:55:in `filter'
mothership-0.5.1/lib/mothership/callbacks.rb:54:in `each'
mothership-0.5.1/lib/mothership/callbacks.rb:54:in `filter'
cf-4.1.1/lib/cf/cli/app/push.rb:79:in `upload_app'
cf-4.1.1/lib/cf/cli/app/push.rb:53:in `sync_app'
cf-4.1.1/lib/cf/cli/app/push.rb:46:in `push'
mothership-0.5.1/lib/mothership/base.rb:66:in `send'
mothership-0.5.1/lib/mothership/base.rb:66:in `run'
mothership-0.5.1/lib/mothership/command.rb:72:in `invoke'
cf-4.1.1/lib/manifests/plugin.rb:137:in `call'
cf-4.1.1/lib/manifests/plugin.rb:137:in `create_and_save_manifest'
mothership-0.5.1/lib/mothership/callbacks.rb:74:in `with_filters'
cf-4.1.1/lib/manifests/plugin.rb:136:in `create_and_save_manifest'
cf-4.1.1/lib/manifests/plugin.rb:75:in `wrap_push'
cf-4.1.1/lib/manifests/plugin.rb:27
mothership-0.5.1/lib/mothership/command.rb:82:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:82:in `invoke'
mothership-0.5.1/lib/mothership/command.rb:86:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:86:in `invoke'
mothership-0.5.1/lib/mothership/base.rb:55:in `execute'
cf-4.1.1/lib/cf/cli.rb:193:in `execute'
cf-4.1.1/lib/cf/cli.rb:204:in `save_token_if_it_changes'
cf-4.1.1/lib/cf/cli.rb:192:in `execute'
cf-4.1.1/lib/cf/cli.rb:128:in `wrap_errors'
cf-4.1.1/lib/cf/cli.rb:188:in `execute'
mothership-0.5.1/lib/mothership.rb:45:in `start'
cf-4.1.1/bin/cf:13
/usr/bin/cf:19:in `load'
/usr/bin/cf:19
```

```
$ cf -v
cf 4.1.1
```

**Comment by andypiper** [comment]
Can you try with 4.1.3 - this works for me.

**Comment by scothis** [comment]
seems to work in 4.1.3
