### ISSUE TITLE
Unable to start application without cf crashing

### ISSUE THREAD

**Issue by scothis** [cloudfoundry-attic/cf#30]
```
$ cf start
/Library/Ruby/Gems/1.8/gems/cfoundry-2.3.5/lib/cfoundry/v2/user.rb:66: warning: don't put space before argument parentheses
Using manifest file manifest.yml

Starting circles... OK
TypeError: can't convert Hash into String
cat ~/.cf/crash # for more details
```

```
Time of crash:
  Wed Jul 10 11:29:28 -0400 2013

TypeError: can't convert Hash into String

/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:560:in `initialize'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:560:in `open'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:560:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/timeout.rb:53:in `timeout'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/timeout.rb:101:in `timeout'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:560:in `connect'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:553:in `do_start'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:542:in `start'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/net/http.rb:440:in `start'
cfoundry-2.3.5/lib/cfoundry/baseclient.rb:108:in `stream_url'
cfoundry-2.3.5/lib/cfoundry/v2/client.rb:82:in `stream_url'
cf-4.1.3/lib/cf/cli/app/start.rb:55:in `stream_start_log'
cf-4.1.3/lib/cf/cli/app/start.rb:28:in `start'
cf-4.1.3/lib/cf/spacing.rb:40:in `spaced'
cf-4.1.3/lib/cf/spacing.rb:38:in `each'
cf-4.1.3/lib/cf/spacing.rb:38:in `spaced'
cf-4.1.3/lib/cf/cli/app/start.rb:17:in `start'
mothership-0.5.1/lib/mothership/base.rb:66:in `send'
mothership-0.5.1/lib/mothership/base.rb:66:in `run'
mothership-0.5.1/lib/mothership/command.rb:72:in `invoke'
cf-4.1.3/lib/manifests/plugin.rb:62:in `call'
cf-4.1.3/lib/manifests/plugin.rb:62:in `wrap_with_optional_name'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in `with_index'
cf-4.1.3/lib/manifests/plugin.rb:60:in `each'
cf-4.1.3/lib/manifests/plugin.rb:60:in `with_index'
cf-4.1.3/lib/manifests/plugin.rb:60:in `wrap_with_optional_name'
cf-4.1.3/lib/manifests/plugin.rb:18
mothership-0.5.1/lib/mothership/command.rb:82:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:82:in `invoke'
mothership-0.5.1/lib/mothership/command.rb:86:in `instance_exec'
mothership-0.5.1/lib/mothership/command.rb:86:in `invoke'
mothership-0.5.1/lib/mothership/base.rb:55:in `execute'
cf-4.1.3/lib/cf/cli.rb:190:in `execute'
cf-4.1.3/lib/cf/cli.rb:201:in `save_token_if_it_changes'
cf-4.1.3/lib/cf/cli.rb:189:in `execute'
cf-4.1.3/lib/cf/cli.rb:125:in `wrap_errors'
cf-4.1.3/lib/cf/cli.rb:185:in `execute'
mothership-0.5.1/lib/mothership.rb:45:in `start'
cf-4.1.3/bin/cf:13
/usr/bin/cf:19:in `load'
/usr/bin/cf:19
```

**Comment by scothis** [comment]
this appears to be resolved in 4.1.4.rc1

**Comment by scothis** [comment]
never-mind, just hit the same issue again

**Comment by scothis** [comment]
This issues goes away with ruby 1.9.3, vs the OS X default 1.8.7.  If a specific version of Ruby is required, cf should say so.  I don't see such a requirement documented anywhere.

**Comment by cf-frontend** [comment]
We've added a note to the readme that Ruby 1.9.x is required. 1.8.7 has been out of major support since June of 2012.

http://www.ruby-lang.org/en/news/2011/10/06/plans-for-1-8-7/
