### ISSUE TITLE
Error when running "cf map-domain <domain>"

### ISSUE THREAD

**Issue by dmikusa** [cloudfoundry-attic/cf#76]
An error is displayed when running "cf map-domain <domain>".

$ cf map-domain some-domain.net
Creating domain some-domain.net... OK
Mapping some-domain.net to my-org... OK
Mapping some-domain.net to development... FAILED
CFoundry::ServerError: 10001: undefined method `space_id=' for #VCAP::CloudController::PrivateDomain:0x007fdab1689488

Despite the error, the domain is still listed when running "cf domains" and it can still be mapped to an application with "cf map".

Version Info:  

cf (5.4.5)
cfoundry (4.7.1)

ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-darwin12.5.0]

Thanks

**Comment by thansmann** [comment]
Hi @dmikusa-pivotal can you also give us the version of Cloud Foundry you're running?

Also, please run the same 'cf' command with the ' --trace' flag:
 cf map-domain some-domain.net --trace 2>&1 | tee ~/cf_map_domain_trace.txt
Please post ~/cf_map_domain_trace.txt to a gist (pasting in issue is to messy :).

@thansmann && @dajulia3

**Comment by dmikusa** [comment]
This is against run.pivotal.io.

```
$ cf target
Target Information (where will apps be pushed):
  CF instance: https://api.run.pivotal.io (API version: 2)
  user: #######
  target app space: ###### (org: #####)
```

```
$ cf map-domain some-domain.net
Creating domain some-domain.net... OK
Mapping some-domain.net to dmikusa... OK
Mapping some-domain.net to development... FAILED
CFoundry::ServerError: 10001: undefined method `space_id=' for #<VCAP::CloudController::PrivateDomain:0x007f72749892a0>
```

```
$ cf domains
Getting domains in ######... OK

name              owner
cfapps.io         none
some-domain.net   #####
```

Will post the output from the command with trace enabled separately, although I would imagine you could replicate it by running the command against run.pivotal.io.  If not, maybe it something with my account.

**Comment by gberche-orange** [comment]
I'm observing this same problem in my automated tests. This problem started being visible on 2013-12-20. Last success test observed at 2013-12-19 20:45:27 (test run bi dayly)

This seems to match the v152 release date according to https://groups.google.com/a/cloudfoundry.org/d/msg/vcap-dev/INmWmUU84jU/4YYXMPCVMiIJ

The problem seems to reside in cloudcontroller, possibly for a deprecated endpoint, here are the traces I have using vcap-java-client:

```
2013-12-20 19:11:55,335 DEBUG [main] org.apache.http.headers(273) - >> POST /v2/domains HTTP/1.1
2013-12-20 19:11:55,335 DEBUG [main] org.apache.http.headers(276) - >> Authorization: bearer ....
2013-12-20 19:11:55,336 DEBUG [main] org.apache.http.headers(276) - >> Accept: text/plain, application/json, */*
2013-12-20 19:11:55,336 DEBUG [main] org.apache.http.headers(276) - >> Content-Type: application/json;charset=UTF-8
2013-12-20 19:11:55,336 DEBUG [main] org.apache.http.headers(276) - >> Content-Length: 115
2013-12-20 19:11:55,337 DEBUG [main] org.apache.http.headers(276) - >> Host: api.run.pivotal.io
2013-12-20 19:11:55,337 DEBUG [main] org.apache.http.headers(276) - >> Connection: Keep-Alive
2013-12-20 19:11:55,337 DEBUG [main] org.apache.http.headers(276) - >> User-Agent: Apache-HttpClient/4.2.4 (java 1.5)
2013-12-20 19:11:55,337 DEBUG [main] org.apache.http.wire(77) - >> "{"wildcard":true,"name":"newdomain.tocreate.com","owning_organization_guid":"b000e2a1-cf62-4ad4-8986-63b12cf95251"}"
2013-12-20 19:11:55,525 DEBUG [main] org.apache.http.wire(63) - << "HTTP/1.1 201 Created[\r][\n]"
2013-12-20 19:11:55,526 DEBUG [main] org.apache.http.wire(63) - << "Content-Type: application/json;charset=utf-8[\r][\n]"
2013-12-20 19:11:55,526 DEBUG [main] org.apache.http.wire(63) - << "Date: Fri, 20 Dec 2013 18:11:55 GMT[\r][\n]"
2013-12-20 19:11:55,526 DEBUG [main] org.apache.http.wire(63) - << "Location: /v2/domains/35759784-92af-4c66-842e-8729450ec69f[\r][\n]"
2013-12-20 19:11:55,527 DEBUG [main] org.apache.http.wire(63) - << "Server: nginx[\r][\n]"
2013-12-20 19:11:55,527 DEBUG [main] org.apache.http.wire(63) - << "X-Cf-Warning: Endpoint deprecated[\r][\n]"
2013-12-20 19:11:55,527 DEBUG [main] org.apache.http.wire(63) - << "X-Content-Type-Options: nosniff[\r][\n]"
2013-12-20 19:11:55,528 DEBUG [main] org.apache.http.wire(63) - << "X-Vcap-Request-Id: 1d6eb86a-56c0-46e2-947a-9c3a43feef65[\r][\n]"
2013-12-20 19:11:55,528 DEBUG [main] org.apache.http.wire(63) - << "Content-Length: 425[\r][\n]"
2013-12-20 19:11:55,529 DEBUG [main] org.apache.http.wire(63) - << "Connection: keep-alive[\r][\n]"
2013-12-20 19:11:55,529 DEBUG [main] org.apache.http.wire(63) - << "[\r][\n]"
2013-12-20 19:11:55,529 DEBUG [main] o.a.h.i.c.DefaultClientConnection(254) - Receiving response: HTTP/1.1 201 Created
2013-12-20 19:11:55,530 DEBUG [main] org.apache.http.headers(257) - << HTTP/1.1 201 Created
2013-12-20 19:11:55,530 DEBUG [main] org.apache.http.headers(260) - << Content-Type: application/json;charset=utf-8
2013-12-20 19:11:55,530 DEBUG [main] org.apache.http.headers(260) - << Date: Fri, 20 Dec 2013 18:11:55 GMT
2013-12-20 19:11:55,531 DEBUG [main] org.apache.http.headers(260) - << Location: /v2/domains/35759784-92af-4c66-842e-8729450ec69f
2013-12-20 19:11:55,531 DEBUG [main] org.apache.http.headers(260) - << Server: nginx
2013-12-20 19:11:55,531 DEBUG [main] org.apache.http.headers(260) - << X-Cf-Warning: Endpoint deprecated
2013-12-20 19:11:55,531 DEBUG [main] org.apache.http.headers(260) - << X-Content-Type-Options: nosniff
2013-12-20 19:11:55,532 DEBUG [main] org.apache.http.headers(260) - << X-Vcap-Request-Id: 1d6eb86a-56c0-46e2-947a-9c3a43feef65
2013-12-20 19:11:55,532 DEBUG [main] org.apache.http.headers(260) - << Content-Length: 425
2013-12-20 19:11:55,532 DEBUG [main] org.apache.http.headers(260) - << Connection: keep-alive
2013-12-20 19:11:55,533 DEBUG [main] o.a.h.i.c.DefaultHttpClient(544) - Connection can be kept alive indefinitely
2013-12-20 19:11:55,533 DEBUG [main] o.c.c.l.r.LoggingRestTemplate(473) - POST request for "https://api.run.pivotal.io/v2/domains" resulted in 201 (Created)
2013-12-20 19:11:55,534 DEBUG [main] o.c.c.l.r.LoggingRestTemplate(78) - Reading [java.lang.String] as "application/json;charset=utf-8" using [org.springframework.http.converter.StringHttpMessageConverter@650f5b42]
2013-12-20 19:11:55,534 DEBUG [main] org.apache.http.wire(63) - << "{[\n]"
2013-12-20 19:11:55,534 DEBUG [main] org.apache.http.wire(63) - << "  "metadata": {[\n]"
2013-12-20 19:11:55,535 DEBUG [main] org.apache.http.wire(63) - << "    "guid": "35759784-92af-4c66-842e-8729450ec69f",[\n]"
2013-12-20 19:11:55,535 DEBUG [main] org.apache.http.wire(63) - << "    "url": "/v2/domains/35759784-92af-4c66-842e-8729450ec69f",[\n]"
2013-12-20 19:11:55,535 DEBUG [main] org.apache.http.wire(63) - << "    "created_at": "2013-12-20T18:11:55+00:00",[\n]"
2013-12-20 19:11:55,536 DEBUG [main] org.apache.http.wire(63) - << "    "updated_at": null[\n]"
2013-12-20 19:11:55,536 DEBUG [main] org.apache.http.wire(63) - << "  },[\n]"
2013-12-20 19:11:55,536 DEBUG [main] org.apache.http.wire(63) - << "  "entity": {[\n]"
2013-12-20 19:11:55,536 DEBUG [main] org.apache.http.wire(63) - << "    "name": "newdomain.tocreate.com",[\n]"
2013-12-20 19:11:55,537 DEBUG [main] org.apache.http.wire(63) - << "    "owning_organization_guid": "b000e2a1-cf62-4ad4-8986-63b12cf95251",[\n]"
2013-12-20 19:11:55,537 DEBUG [main] org.apache.http.wire(63) - << "    "owning_organization_url": "/v2/organizations/b000e2a1-cf62-4ad4-8986-63b12cf95251"[\n]"
2013-12-20 19:11:55,537 DEBUG [main] org.apache.http.wire(63) - << "  }[\n]"
2013-12-20 19:11:55,538 DEBUG [main] org.apache.http.wire(77) - << "}"

2013-12-20 19:11:55,548 DEBUG [main] org.apache.http.headers(273) - >> PUT /v2/spaces/2e5aee21-45fe-4032-a4d5-72e09035e170/domains/35759784-92af-4c66-842e-8729450ec69f HTTP/1.1
2013-12-20 19:11:55,548 DEBUG [main] org.apache.http.headers(276) - >> Authorization: ....
2013-12-20 19:11:55,549 DEBUG [main] org.apache.http.headers(276) - >> Content-Type: application/json;charset=UTF-8
2013-12-20 19:11:55,549 DEBUG [main] org.apache.http.headers(276) - >> Content-Length: 2
2013-12-20 19:11:55,549 DEBUG [main] org.apache.http.headers(276) - >> Host: api.run.pivotal.io
2013-12-20 19:11:55,549 DEBUG [main] org.apache.http.headers(276) - >> Connection: Keep-Alive
2013-12-20 19:11:55,550 DEBUG [main] org.apache.http.headers(276) - >> User-Agent: Apache-HttpClient/4.2.4 (java 1.5)
2013-12-20 19:11:55,550 DEBUG [main] org.apache.http.wire(77) - >> "{}"

2013-12-20 19:11:55,719 DEBUG [main] org.apache.http.wire(63) - << "HTTP/1.1 500 Internal Server Error[\r][\n]"
2013-12-20 19:11:55,720 DEBUG [main] org.apache.http.wire(63) - << "Content-Type: application/json;charset=utf-8[\r][\n]"
2013-12-20 19:11:55,720 DEBUG [main] org.apache.http.wire(63) - << "Date: Fri, 20 Dec 2013 18:11:55 GMT[\r][\n]"
2013-12-20 19:11:55,721 DEBUG [main] org.apache.http.wire(63) - << "Server: nginx[\r][\n]"
2013-12-20 19:11:55,721 DEBUG [main] org.apache.http.wire(63) - << "X-Cf-Warning: Endpoint deprecated[\r][\n]"
2013-12-20 19:11:55,722 DEBUG [main] org.apache.http.wire(63) - << "X-Content-Type-Options: nosniff[\r][\n]"
2013-12-20 19:11:55,722 DEBUG [main] org.apache.http.wire(63) - << "X-Vcap-Request-Id: 5effdb5c-cd0c-4b3f-b2b3-6a45ec8d1169[\r][\n]"
2013-12-20 19:11:55,722 DEBUG [main] org.apache.http.wire(63) - << "Content-Length: 10311[\r][\n]"
2013-12-20 19:11:55,723 DEBUG [main] org.apache.http.wire(63) - << "Connection: keep-alive[\r][\n]"
2013-12-20 19:11:55,723 DEBUG [main] org.apache.http.wire(63) - << "[\r][\n]"
2013-12-20 19:11:55,723 DEBUG [main] o.a.h.i.c.DefaultClientConnection(254) - Receiving response: HTTP/1.1 500 Internal Server Error
2013-12-20 19:11:55,724 DEBUG [main] org.apache.http.headers(257) - << HTTP/1.1 500 Internal Server Error
2013-12-20 19:11:55,724 DEBUG [main] org.apache.http.headers(260) - << Content-Type: application/json;charset=utf-8
2013-12-20 19:11:55,724 DEBUG [main] org.apache.http.headers(260) - << Date: Fri, 20 Dec 2013 18:11:55 GMT
2013-12-20 19:11:55,725 DEBUG [main] org.apache.http.headers(260) - << Server: nginx
2013-12-20 19:11:55,725 DEBUG [main] org.apache.http.headers(260) - << X-Cf-Warning: Endpoint deprecated
2013-12-20 19:11:55,725 DEBUG [main] org.apache.http.headers(260) - << X-Content-Type-Options: nosniff
2013-12-20 19:11:55,726 DEBUG [main] org.apache.http.headers(260) - << X-Vcap-Request-Id: 5effdb5c-cd0c-4b3f-b2b3-6a45ec8d1169
2013-12-20 19:11:55,726 DEBUG [main] org.apache.http.headers(260) - << Content-Length: 10311
2013-12-20 19:11:55,726 DEBUG [main] org.apache.http.headers(260) - << Connection: keep-alive
2013-12-20 19:11:55,727 DEBUG [main] o.a.h.i.c.DefaultHttpClient(544) - Connection can be kept alive indefinitely
2013-12-20 19:11:55,727 WARN  [main] o.c.c.l.r.LoggingRestTemplate(486) - PUT request for "https://api.run.pivotal.io/v2/spaces/2e5aee21-45fe-4032-a4d5-72e09035e170/domains/35759784-92af-4c66-842e-8729450ec69f" resulted in 500 (Internal Server Error); invoking error handler
2013-12-20 19:11:55,729 DEBUG [main] org.apache.http.wire(77) - << "{"code":10001,"description":"undefined method `space_id=' for #<VCAP::CloudController::PrivateDomain:0x007f7f3ab9c358>",
    "error_code":"CF-NoMethodError",
    "types":["NoMethodError",
    "NameError"],"backtrace":[
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sequel-3.48.0/lib/sequel/model/associations.rb:1435:in `block (2 levels) in def_one_to_many'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sequel-3.48.0/lib/sequel/model/associations.rb:1435:in `each'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sequel-3.48.0/lib/sequel/model/associations.rb:1435:in `block in def_one_to_many'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sequel-3.48.0/lib/sequel/model/associations.rb:1587:in `add_associated_object'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sequel-3.48.0/lib/sequel/model/associations.rb:1153:in `block in def_add_method'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/sequel_plugins/vcap_relations.rb:135:in `block in define_to_many_methods'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/rest_controller/model_controller.rb:179:in `do_related'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/rest_controller/model_controller.rb:141:in `add_related'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/rest_controller/base.rb:95:in `dispatch'",
     "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb:56:in `block (2 levels) in define_to_many_routes'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb:18:in `yield'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/lib/cloud_controller/rest_controller/routes.rb:18:in `block in define_route'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:1540:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:1540:in `block in compile!'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `[]'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `block (3 levels) in route!'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:966:in `route_eval'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.9.171/lib/new_relic/agent/instrumentation/sinatra.rb:133:in `route_eval_with_newrelic'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:950:in `block (2 levels) in route!'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:987:in `block in process_route'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:985:in `catch'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:985:in `process_route'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.9.171/lib/new_relic/agent/instrumentation/sinatra.rb:116:in `process_route_with_newrelic'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:948:in `block in route!'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:947:in `each'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:947:in `route!'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:1059:in `block in dispatch!'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `block in invoke'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `catch'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `invoke'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:1056:in `dispatch!'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.9.171/lib/new_relic/agent/instrumentation/sinatra.rb:151:in `dispatch_and_notice_errors_with_newrelic'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.9.171/lib/new_relic/agent/instrumentation/sinatra.rb:146:in `block in dispatch_with_newrelic'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.9.171/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:339:in `perform_action_with_newrelic_trace'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.9.171/lib/new_relic/agent/instrumentation/sinatra.rb:145:in `dispatch_with_newrelic'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:882:in `block in call!'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `block in invoke'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `catch'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:1041:in `invoke'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:882:in `call!'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:870:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.9.171/lib/new_relic/rack/error_collector.rb:50:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.9.171/lib/new_relic/rack/browser_monitoring.rb:23:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.6.9.171/lib/new_relic/rack/agent_hooks.rb:28:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/rack-protection-1.5.0/lib/rack/protection/xss_header.rb:18:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/rack-protection-1.5.0/lib/rack/protection/path_traversal.rb:16:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/rack-protection-1.5.0/lib/rack/protection/json_csrf.rb:18:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/rack-protection-1.5.0/lib/rack/protection/base.rb:49:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/rack-protection-1.5.0/lib/rack/protection/base.rb:49:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/rack-protection-1.5.0/lib/rack/protection/frame_options.rb:31:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:175:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:1949:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/commonlogger.rb:33:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:212:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/thin-1.5.1/lib/thin/connection.rb:81:in `block in pre_process'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/thin-1.5.1/lib/thin/connection.rb:79:in `catch'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/thin-1.5.1/lib/thin/connection.rb:79:in `pre_process'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in `call'",
    "/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/eventmachine-1.0.3/lib/eventmachine.rb:1037:in `block in spawn_threadpool'"]}[\n]"
```

**Comment by atomanyih** [comment]
This issue is being addressed as an issue with cloud controller. Closing.
Thanks @dmikusa-pivotal, @gberche-orange 

-CF Community Pair (@atomanyih & @sclevine)
